[package]
name = "vecmat"
version = "0.3.0"
authors = ["Alexey Gerasev <alexey.gerasev@gmail.com>"]
description = "Lightweight low-dimensional vector and matrix library"
documentation = "https://nthend.github.io/vecmat-rs/target/doc/vecmat/"
homepage = "https://github.com/nthend/vecmat-rs"
repository = "https://github.com/nthend/vecmat-rs"
readme = "README.md"
keywords = ["vector", "matrix", "math"]
categories = ["algorithms", "data-structures", "science"]
license = "MIT/Apache-2.0"

[badges]
travis-ci = { repository = "nthend/vecmat-rs" }

[dependencies]
num-traits = "0.2"
num-integer = "0.1"
