[package]
name = "vecmat"
version = "0.2.1"
authors = ["Alexey Gerasev <alexey.gerasev@gmail.com>"]
description = "Lightweight low-dimensional vector and matrix library"
documentation = "https://nthend.github.io/vecmat-rs/target/doc/vecmat/"
homepage = "https://github.com/nthend/vecmat-rs"
repository = "https://github.com/nthend/vecmat-rs"
keywords = ["vector", "matrix", "math"]
categories = ["algorithms", "data-structures"]
license = "MIT/Apache-2.0"

[badges]
travis-ci = { repository = "https://github.com/nthend/vecmat-rs", branch = "master" }

[dependencies]
num-traits = "0.1.37"
num-integer = "0.1.34"
