on: [push, pull_request]

jobs:
  build_and_test:
    name: vecmat
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo test --no-default-features
      - run: cargo test
